services:
  postgres:
    image: postgres:16
    container_name: employee-attendance-postgres
    restart: unless-stopped
    environment:
      POSTGRES_DB: employee_attendance
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  audit-postgres:
    image: postgres:16
    container_name: employee-attendance-audit-postgres
    restart: unless-stopped
    environment:
      POSTGRES_DB: employee_audit_log
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5433:5432"
    volumes:
      - audit_postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
  audit_postgres_data:
